### ISSUE TITLE
ChemDraw 18-21  不能预测熔、沸点等性质。

### ISSUE THREAD

**Issue by Git123HubLee** [Z-H-Sun/CS_CCME_Posts#9] opened 2022-05-15 06:23 UTC
您好！首先特别感谢您的成果，给我们使用者提供了方便。
按您的方法试了版本17、18、19、20、21，都比直接替换的好，但有一个问题不知道您是否发现，除了17版，18、19、20、21都不能正常预测分子化学性质（chemical properties）：

![Snipaste_2022-05-15_14-17-23](https://user-images.githubusercontent.com/105578334/168459878-2082e643-4be3-4afd-ac19-e7884264581f.jpg)

这几个版本试了几次，运行COS_Win_Patch时，都是绿色提示通过，应该是正常激活的了。
不知是哪里出了问题？

**Comment by prenfic** [comment] 2022-05-15 15:36
FYI，我测试了一下mac版本
以methanol为例
没任何问题
[image: image.png]

**Comment by prenfic** [comment] 2022-05-15 15:37
[image: image.png]
Just in case，看了下Benzene，也没遇到问题

**Comment by Git123HubLee** [comment] 2022-05-16 02:26
换台电脑试了一下，都正常的。
应该我那台PC哪里出了问题。
谢谢你的回复！
Thanks

**Comment by Z-H-Sun** [comment] 2022-05-17 03:34
I have never met such problems, so I have no idea. Maybe just some issue with Windows 11, which I have never tested on.

I am closing this issue. Let me know if there is any update, or anyone else is experiencing the same issue.

**Closed by Z-H-Sun** 2022-05-17 03:34 UTC

**Comment by Git123HubLee** [comment] 2022-05-20 13:35
确实应该是win11的问题。两台win11都不行，另两台分别win10和win7是正常的。

**Comment by prenfic** [comment] 2022-05-20 16:46
My goodness，那我早上用win11试试看能复现这问题么。我已经好多年没用Windows版本的chemdraw了

Regards,
Kaijian Lawrence Law
loc

**Comment by Z-H-Sun** [comment] 2022-05-20 19:49
My impression is that Windows 11 is not a good OS for productivity. I have a laptop shipped with Windows 11. From my observation, I have received Windows Update notifications very frequently, which is not a good sign and indicates the OS is not stable enough. Moreover, I have experienced incompatibility issues with some hardware drives when I connected it with some instruments. Since then, I have decided not to rely heavily on that computer, which I have mainly used to browse the web and reply emails.

**Comment by Z-H-Sun** [comment] 2022-11-18 07:29
@Git123HubLee The latest CD 22.0 can display those predictions properly (tested on the latest Win 11). Either Microsoft or PerkinElmer has fixed this bug. I have already uploaded the cracked installer for this latest version in the Baidu/GDrive shared folder, so you can download it from there (and I will also update the article soon).

**Comment by Git123HubLee** [comment] 2022-11-18 07:56
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Thank you very much！
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年11月18日 15:29
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [Z-H-Sun/CS_CCME_Posts] ChemDraw 18-21  不能预测熔、沸点等性质。 (Issue #9)
        
      
    
  
  
@Git123HubLee The latest CD 22.0 can display those predictions properly (tested on the latest Win 11). Either Microsoft or PerkinElmer has fixed this bug. I have already uploaded the cracked installer for this latest version in the Baidu/GDrive shared folder, so you can download it from there (and I will also update the article soon).

**Comment by Z-H-Sun** [comment] 2022-11-18 15:52
Maybe try updating your Win 11? It is fine on my side (Version 21H2, 22000.1219). See screenshot below.
![10 50 02 590](https://user-images.githubusercontent.com/48094808/202745858-109187b5-8a06-479e-9289-d94f843e006f.png)

**Comment by Z-H-Sun** [comment] 2022-11-19 01:06
So I tried CD 20 on Win11, which can also give correct values. Then it should not be PerkinElmer's issue. To further troubleshoot, maybe try the following:

* Upgrade Win11
* Restore all the cracked programs and use [this latest patch](https://github.com/Z-H-Sun/MRN-ADF_Patch/releases/download/v2.15/COS_Win_Patch.exe) to crack chem office again. The older patches might be flawed.
* Uninstall and reinstall the .NET framework required by the chem office (for 22.0, the version is .NET 4.8)

![13 40 01 391](https://user-images.githubusercontent.com/48094808/202826494-0e9aaad0-40f1-4fed-925a-dceee06b4d6c.png)

**Comment by Git123HubLee** [comment] 2022-11-19 06:50
非常感谢您的回复。
但我的两台Win11，依然不行，其中一台还重新初始化过。win11内置了 .NET 4.8，试图重新安装4.8、4.81版，但提示已经安装更高版，无法继续。

**Comment by Git123HubLee** [comment] 2022-11-19 06:58
非常感谢您的回复。
但我的两Win11依然不行，其中一台重新恢复过。chem office也是完全卸载后重新安装的。win11内置了.NET 4.8，试图重装安装4.8、4.81版均提示已经安装更高版，无法继续。
![Snipaste_2022-11-19_14-46-09](https://user-images.githubusercontent.com/105578334/202838852-09ccb0ba-7aaf-4bb5-8efe-f8e958169058.jpg)
![Snipaste_2022-11-19_14-34-09](https://user-images.githubusercontent.com/105578334/202838856-6dc7f2ab-7059-4e63-bfdc-e58ef7672e94.jpg)
![Snipaste_2022-11-19_14-34-44](https://user-images.githubusercontent.com/105578334/202838877-ef513897-03bb-4fe4-a7dd-f7435188df9c.jpg)

**Comment by Git123HubLee** [comment] 2022-11-19 07:00
感觉可能有还是其它原因。不知道是否也有其他用户碰到这个样的问题？

**Comment by Z-H-Sun** [comment] 2022-11-19 08:10
What would happen if you click "report"? What does the report say?

I just realize the OS I have been using is still 21H2, so I will upgrade to 22H2 and retest

**Comment by Git123HubLee** [comment] 2022-11-19 08:18
click "report"：
![Snipaste_2022-11-19_16-14-00](https://user-images.githubusercontent.com/105578334/202841584-aba953ea-8f88-4f86-ae4a-549ec25e2181.jpg)
会出现：
记事本，系统找不到系统路径：
![image](https://user-images.githubusercontent.com/105578334/202841642-ef4f5fd2-837f-4ba6-94a5-8c37bb969213.png)
难不成是我把这个改动过？
![image](https://user-images.githubusercontent.com/105578334/202841700-3ece0858-f7ba-4640-ba31-d490ed27405e.png)
恢复一下试试

**Comment by Z-H-Sun** [comment] 2022-11-19 08:21
I think it might be better to remove the CJK characters in your temp folder? Basically, CD will open a .tmp file in the %TEMP% folder.

**Comment by Git123HubLee** [comment] 2022-11-19 11:49
您说的CJK characters，我在temp文件夹下并没有找到。我重新试下17，18，20版，表现各不相同：
17能正常正常预测，点击“report”能正常打开文件，文件名为CP2.tmp，在D:\用户\Temp下。
18不能正常预测，但“report”能正常打开文件，只能里面没有预测的数值。也是在D:\用户\Temp下。
![image](https://user-images.githubusercontent.com/105578334/202848696-eed58b01-6ac5-4a2a-84c5-2df72dc9de91.png)
20不能正常预测，点击“report”无响应。
22，就是之前向反映的“report”记事本找不到指定路径，D:\用户\Temp下也生成的文件。chem office安装在C和D盘，结果一样。
实在不行，只能再回到17版用了，因为这个功能我用的比较频繁。
再次感谢您的回复。

**Comment by Z-H-Sun** [comment] 2022-11-23 04:32
> 您说的CJK characters，我在temp文件夹下并没有找到。

That is not what I meant. I meant to say the Chinese characters "用户" in your path (folder name). But that does not seem to be the major reason, since you said the following:

> 18不能正常预测，但“report”能正常打开文件，只能里面没有预测的数值。也是在D:\用户\Temp下。

So even if the presence of CJK characters is the reason why `Notepad` says "cannot find path," there are other things that prevents the prediction of CD.

On a different note, I previously said:

> I just realize the OS I have been using is still 21H2, so I will upgrade to 22H2 and retest

I updated my Win11 to 22H2, but on my side, ***I can still see correctly displayed predictions in the chemical properties window***. Therefore, this fact led me to doubt if there is conflict between CD and other software you installed, e.g. anti-virus software: If the anti-virus software blocks the function of, say, `CambridgeSoft.ChemOffice.ChemPropPro.dll`, then of course you cannot find it working.

Since I cannot reproduce your issue, there is nothing I can further help.

One last thing you can possibly try is installing and running the software in `Windows Sandbox`, which basically provides the same OS as your physical computer but on an isolated environment so as to exclude influence from other factors like other software you installed.

> 实在不行，只能再回到17版用了，因为这个功能我用的比较频繁。

Reasonable.

**Comment by Git123HubLee** [comment] 2022-11-23 14:09
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    很高兴，找到原因了。就是要恢复“临时文件”至C盘默认位置就行了。
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年11月23日 12:32
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [Z-H-Sun/CS_CCME_Posts] ChemDraw 18-21  不能预测熔、沸点等性质。 (Issue #9)
        
      
    
  
  



您说的CJK characters，我在temp文件夹下并没有找到。



That is not what I meant. I meant to say the Chinese characters "用户" in your path (folder name). But that does not seem to be the major reason, since you said the following:



18不能正常预测，但“report”能正常打开文件，只能里面没有预测的数值。也是在D:\用户\Temp下。



So even if the presence of CJK characters is the reason why Notepad says "cannot find path," there are other things that prevents the prediction of CD.

On a different note, I previously said:



I just realize the OS I have been using is still 21H2, so I will upgrade to 22H2 and retest



I updated my Win11 to 22H2, but on my side, I can still see correctly displayed predictions in the chemical properties window. Therefore, this fact led me to doubt if there is conflict between CD and other software you installed, e.g. anti-virus software: If the anti-virus software blocks the function of, say, CambridgeSoft.ChemOffice.ChemPropPro.dll, then of course you cannot find it working.

Since I cannot reproduce your issue, there is nothing I can further help.

One last thing you can possibly try is installing and running the software in Windows Sandbox, which basically provides the same OS as your physical computer but on an isolated environment so as to exclude influence from other factors like other software you installed.



实在不行，只能再回到17版用了，因为这个功能我用的比较频繁。



Reasonable.
